@extends('layouts.app')
@section('header', 'Kerjakan Kuis')
@section('content')
<div class="mx-auto max-w-3xl pb-32" x-data="quizPlayer(@js($questions), '{{ $attempt['Deadline_At'] }}')" x-init="startTimer">
    <div class="sticky top-16 z-20 mb-4 rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur lg:top-4"><div class="flex items-center justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wide text-sky-600" x-text="`${index+1} dari ${questions.length}`"></p><h2 class="line-clamp-1 font-black">{{ $quiz['Title'] }}</h2></div><div role="timer" aria-live="polite" class="rounded-xl bg-slate-900 px-4 py-2 text-center text-white"><span class="block text-[10px] font-bold uppercase">Sisa waktu</span><strong class="font-mono text-xl" x-text="clock"></strong></div></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full bg-sky-500 transition-all" :style="`width:${((index+1)/questions.length)*100}%`"></div></div></div>
    <form method="POST" action="{{ route('student.quizzes.submit',$attempt['Attempt_ID']) }}" @submit="if(!confirm('Kirim jawaban final? Jawaban tidak dapat diubah setelah dikirim.')){$event.preventDefault()}">@csrf
        <template x-for="(q,i) in questions" :key="q.Question_ID"><fieldset x-show="index===i" class="rounded-2xl bg-white p-5 shadow-sm sm:p-7"><legend class="sr-only" x-text="`Soal ${i+1}`"></legend><p class="text-lg font-black leading-relaxed" x-text="q.Question_Text"></p><div class="mt-6 space-y-3"><template x-for="letter in ['A','B','C','D']"><label class="flex min-h-14 cursor-pointer items-center gap-3 rounded-xl border-2 p-4 transition focus-within:ring-2 focus-within:ring-sky-500" :class="answers[q.Question_ID]===letter?'border-sky-500 bg-sky-50':'border-slate-200'"><input type="radio" :name="`answers[${q.Question_ID}]`" :value="letter" x-model="answers[q.Question_ID]" class="h-5 w-5"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-slate-100 font-black" x-text="letter"></span><span class="font-semibold" x-text="q[`Option_${letter}`]"></span></label></template></div></fieldset></template>
        <div class="mt-4 flex gap-3"><button type="button" @click="index--" :disabled="index===0" class="min-h-12 flex-1 rounded-xl border border-slate-300 bg-white font-black disabled:opacity-40">Sebelumnya</button><button type="button" x-show="index<questions.length-1" @click="index++" class="min-h-12 flex-1 rounded-xl bg-sky-600 font-black text-white">Berikutnya</button><button type="submit" x-show="index===questions.length-1" class="min-h-12 flex-1 rounded-xl bg-emerald-600 font-black text-white">Kirim Jawaban</button></div>
        <div class="mt-4 flex flex-wrap gap-2" aria-label="Status jawaban"><template x-for="(q,i) in questions"><button type="button" @click="index=i" class="h-10 w-10 rounded-lg border font-bold" :class="answers[q.Question_ID]?'border-emerald-400 bg-emerald-50 text-emerald-800':'border-slate-300 bg-white text-slate-500'" :aria-label="`Soal ${i+1}, ${answers[q.Question_ID]?'sudah':'belum'} dijawab`" x-text="i+1"></button></template></div>
    </form>
</div>
@push('scripts')<script>function quizPlayer(questions,deadline){return{questions,index:0,answers:{},clock:'--:--',timer:null,startTimer(){const tick=()=>{const left=Math.max(0,new Date(deadline.replace(' ','T')+'+07:00').getTime()-Date.now());this.clock=`${String(Math.floor(left/60000)).padStart(2,'0')}:${String(Math.floor((left%60000)/1000)).padStart(2,'0')}`;if(left===0)clearInterval(this.timer)};tick();this.timer=setInterval(tick,1000)}}}</script>@endpush
@endsection
