<?php

namespace App\Helpers;

use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Facades\Auth;

class ReportHelper
{
    /**
     * Determine Export Mode based on request
     * 
     * @param string $format 'pdf', 'excel', 'csv', 'print'
     * @param string $moduleName e.g. 'USERS'
     * @param \Illuminate\Support\Collection $data
     * @param array $metadata Custom metadata (summary, etc)
     * @param string $pdfView Blade view path for PDF
     * @param array $headers For CSV/Excel
     * @param callable $mapRow Callback to map data to CSV/Excel row
     */
    public static function export(
        $format,
        $moduleName,
        $data,
        $metadata,
        $pdfView,
        $headers = [],
        $mapRow = null,
        $isLandscape = false
    ) {
        $timestamp = date('Ymd_His');
        $filename = strtoupper($moduleName) . '_' . $timestamp;
        
        $metadata['reportTitle'] = strtoupper($moduleName) . ' REPORT';
        $metadata['documentNumber'] = 'REP-' . date('Ymd') . '-' . rand(100000, 999999);
        $metadata['generatedBy'] = Auth::check() ? Auth::user()->Full_Name ?? 'Administrator' : 'System';
        $metadata['generatedDate'] = now()->format('d F Y, H:i:s') . ' WIB';
        $metadata['totalRecords'] = $data->count();
        $metadata['version'] = '1.0.0';
        
        // QR Code string: Document Number | Timestamp | Generated By | Version | Hash
        $qrString = "DOC:{$metadata['documentNumber']} | TIME:{$timestamp} | BY:{$metadata['generatedBy']} | VER:1.0.0 | HASH:" . md5($timestamp . $moduleName);
        
        // Use inline SVG for QR code if simplesoftwareio/simple-qrcode is available
        if (class_exists('\SimpleSoftwareIO\QrCode\Facades\QrCode')) {
            try {
                $metadata['qrCodeSvg'] = \SimpleSoftwareIO\QrCode\Facades\QrCode::size(80)->generate($qrString);
            } catch (\Exception $e) {
                $metadata['qrCodeSvg'] = null;
            }
        } else {
            $metadata['qrCodeSvg'] = null;
        }
        
        $metadata['records'] = $data;
        $metadata['headers'] = $headers;
        $metadata['mapRow'] = $mapRow;

        if ($format === 'pdf' || $format === 'preview') {
            return self::generatePdf($filename, $pdfView, $metadata, $format === 'preview', $isLandscape);
        }

        if ($format === 'csv') {
            return self::generateCsv($filename, $data, $headers, $mapRow);
        }

        if ($format === 'excel') {
            return self::generateExcel($filename, $data, $headers, $mapRow);
        }

        if ($format === 'print') {
            $metadata['isPrintMode'] = true;
            return view($pdfView, $metadata);
        }

        abort(400, 'Invalid export format');
    }

    private static function generatePdf($filename, $view, $data, $isPreview, $isLandscape)
    {
        $pdf = Pdf::loadView($view, $data);
        
        if ($isLandscape) {
            $pdf->setPaper('A4', 'landscape');
        } else {
            $pdf->setPaper('A4', 'portrait');
        }

        // Add Metadata for Adobe Reader
        $pdf->getDomPDF()->getOptions()->set(['defaultFont' => 'Helvetica', 'isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true]);
        
        // Metadata (using dompdf direct access if possible, or standard way)
        $dompdf = $pdf->getDomPDF();
        $dompdf->addInfo('Title', $data['reportTitle']);
        $dompdf->addInfo('Author', $data['generatedBy']);
        $dompdf->addInfo('Creator', 'WAKAMIYA MANAGEMENT SYSTEM');
        $dompdf->addInfo('Subject', 'Enterprise Executive Report');
        $dompdf->addInfo('Keywords', 'WMS, Report, ' . $data['reportTitle']);

        if ($isPreview) {
            return $pdf->stream($filename . '.pdf', ['Attachment' => false]);
        }

        return $pdf->download($filename . '.pdf');
    }

    public static function sanitizeCsvCell($value)
    {
        if (is_string($value) && preg_match('/^[=\-+\@]/', $value)) {
            return "'" . $value;
        }
        return $value;
    }

    private static function generateCsv($filename, $data, $headers, $mapRow)
    {
        $headersArr = ['Content-Type' => 'text/csv; charset=UTF-8', 'Content-Disposition' => "attachment; filename=\"$filename.csv\""];

        $callback = function() use($data, $headers, $mapRow) {
            $file = fopen('php://output', 'w');
            
            // UTF-8 BOM for Excel compatibility
            fputs($file, "\xEF\xBB\xBF");
            
            if (!empty($headers)) {
                $sanitizedHeaders = array_map([self::class, 'sanitizeCsvCell'], $headers);
                fputcsv($file, $sanitizedHeaders);
            }
            foreach ($data as $row) {
                $mapped = $mapRow($row);
                $sanitizedRow = array_map([self::class, 'sanitizeCsvCell'], $mapped);
                fputcsv($file, $sanitizedRow);
            }
            fclose($file);
        };

        return response()->stream($callback, 200, $headersArr);
    }

    private static function generateExcel($filename, $data, $headers, $mapRow)
    {
        // HTML to XLS fallback (very reliable for simple tables and supports colors/bold)
        $html = "<html xmlns:x=\"urn:schemas-microsoft-com:office:excel\">
        <head>
            <!--[if gte mso 9]>
            <xml>
                <x:ExcelWorkbook>
                    <x:ExcelWorksheets>
                        <x:ExcelWorksheet>
                            <x:Name>Sheet1</x:Name>
                            <x:WorksheetOptions>
                                <x:DisplayGridlines/>
                            </x:WorksheetOptions>
                        </x:ExcelWorksheet>
                    </x:ExcelWorksheets>
                </x:ExcelWorkbook>
            </xml>
            <![endif]-->
        </head>
        <body>
        <table><tr>";
        foreach ($headers as $h) {
            $html .= "<th style='background-color:#cccccc;font-weight:bold;border:1px solid #000;'>" . htmlspecialchars((string) self::sanitizeCsvCell($h), ENT_QUOTES, 'UTF-8') . "</th>";
        }
        $html .= "</tr>";
        
        foreach ($data as $row) {
            $mapped = $mapRow($row);
            $html .= "<tr>";
            foreach ($mapped as $cell) {
                $html .= "<td style='border:1px solid #000;'>" . htmlspecialchars((string) self::sanitizeCsvCell($cell ?? ''), ENT_QUOTES, 'UTF-8') . "</td>";
            }
            $html .= "</tr>";
        }
        $html .= "</table></body></html>";

        return response($html)
            ->header('Content-Type', 'application/vnd.ms-excel')
            ->header('Content-Disposition', 'attachment; filename="' . $filename . '.xls"');
    }
}
