<div class="my-8">
    <h2 class="text-lg font-bold text-slate-800 mb-4">{{ $document['Title'] ?? 'General Document' }}</h2>
    <div class="text-sm text-slate-700 leading-relaxed space-y-4">
        {{ $document['Message'] ?? 'This document was automatically generated by the WMS Document Engine. Content layout is set to default.' }}
    </div>
    
    <table class="w-full text-left text-xs mt-8 border-collapse">
        <tbody>
            <tr>
                <th class="py-2 border-b border-slate-200 w-1/3">Reference Module</th>
                <td class="py-2 border-b border-slate-200">{{ $document['Reference_Module'] ?? '-' }}</td>
            </tr>
            <tr>
                <th class="py-2 border-b border-slate-200">Reference ID</th>
                <td class="py-2 border-b border-slate-200">{{ $document['Reference_ID'] ?? '-' }}</td>
            </tr>
            <tr>
                <th class="py-2 border-b border-slate-200">Status</th>
                <td class="py-2 border-b border-slate-200">{{ $document['Status'] ?? '-' }}</td>
            </tr>
        </tbody>
    </table>
</div>



